services:
  app:
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USER_NAME: ${USER_NAME:-vscode}
    volumes:
      - ../app/:/opt/app
      - ~/.ssh:/home/${USER_NAME:-vscode}/.ssh:ro # 読み取り専用としてssh用の秘密鍵をマウント。
      - ~/.gitconfig:/home/${USER_NAME:-vscode}/.gitconfig
    stdin_open: true
    tty: true